version: "3.8"
services:
  front:
    build:
      context: ./front
    container_name: kms_front
    volumes:
      - ./front/:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - back

  back:
    build:
      context: ./back
    container_name: kms_back
    volumes:
      - ./back/:/app
      - /app/node_modules
    restart: always
    ports:
      - "8000:8000"
